# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Molly Lloyd
email: mollylloyd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Molly Lloyd is a software engineer based in San Francisco. These are her brain blobs. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mollylloyd.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:categories/:title


port: 8080
host: 127.0.0.1

jems:
- jemoji


navlinks:
- title: Code
  url: /code/
- title: Projects
  url: /projects/
- title: Resume
  url: /resume/

social:
- text: Github
  url: https://github.com/mollymerp
  icon: github-alt
- text: Twitter
  url: https://twitter.com/mollymerp
  icon: twitter
- text: Instagram
  url: http://instagram.com/mollymerp
  icon: instagram
- text: feed
  url: http://mollylloyd.me/feed.xml
  icon: rss
- text: Email
  url: mailto:mollylloyd@gmail.com
  icon: send-o
